### ISSUE TITLE
在MACOS系统下，sublime安装此插件后，右击侧边栏无法新建文件或者文件夹

### ISSUE THREAD

**Issue by changjiawen** [52fisher/SideBarEnhancements#9]
在MACOS系统下，sublime安装此插件后，右击侧边栏无法新建文件或者文件夹

**Comment by 52fisher** [comment]
![图片](https://user-images.githubusercontent.com/32198215/151862372-5fc68408-6995-4e92-87ba-59eb30f8607e.png)
请确保你在使用 SideBarEnhancements时是对一个文件夹（项目）进行操作（红色部分），如果对单独的一个文件（黄色部分），右键菜单不会产生任何反应。如果在项目中无法正常使用，请根据[安装故障排除](https://github.com/52fisher/SideBarEnhancements#%E5%AE%89%E8%A3%85%E6%95%85%E9%9A%9C%E6%8E%92%E9%99%A4)中的描述进行重新安装。
